### ISSUE TITLE
[BUG] App does not go past permissions screen

### ISSUE THREAD

**Issue by Devnol** [moseoridev/WarpShare#7]
**Describe the bug**
Opening the app for the first time, you are asked to grant permissions. After granting those, that screen does not go away at all.

**To Reproduce**
1. Install latest apk
2. Open app
3. Grant permissions
4. Nothing happens
5. Tapping the "grant permissions" button again shows a popup to open settings and grant permissions from there, although all permissions have already been granted.

**Expected behavior**
For some other screen to show up

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A12
 - OS: Android 12 (OneUI Core 4.1)

**Comment by Georg-007** [comment]
Does it ask for nearby devices permission?
I had the same issue on an older phone with android 8.1 where Bluetooth permission is included in GPS. I removed the Bluetooth permission check and granted GPS permission manually (for some reason it's already listed in permissions) and it worked. I don't know in which android version the nearby devices permission was invented, maybe you issue isn't related to this.

**Comment by Georg-007** [comment]
If it asks for nearby devices permission your issue isn't related to mine and there's no need for granting location permission (in app info).
Maybe your issue is also because of Samsung's One UI for some reason isn't supported.

**Comment by liapisn** [comment]
Same here 
* Xiaomi MI 8
* Android 10 (MIUI 12)

**Comment by AhmedBinSohail** [comment]
Same here. Google Pixel 4.
Android 12.

**Comment by Yug1900** [comment]
Same issue Samsung S9+ With Snapdragon Chip Android 10

**Comment by taesungh** [comment]
Had this issue initially but quickly resolved by **making sure wi-fi and bluetooth are enabled**.
No other permissions needed to be granted besides "Files and media".
OnePlus 6, OxygenOS 11.

**Comment by Glenry** [comment]
@taesungh, turning on both wifi and Bluetooth then open the app, worked for me, I'm on Samsung Galaxy A12 Android 12 (One UI 4.1)

**Comment by musakahero** [comment]
> Had this issue initially but quickly resolved by **making sure wi-fi and bluetooth are enabled**.
> No other permissions needed to be granted besides "Files and media".
> OnePlus 6, OxygenOS 11.

Tried this, the issue remains. 
Enabled wifi and Bluetooth > permitted all permissions available > cleared cache > started the app, same permissions-asking screen.

**Comment by Devnol** [comment]
I tried turning bt and wifi on, closed and reopened the app like some people suggested. The grant permissions page does disappear but the only thing that shows is the WarpShare text in the top bar, just like in basic android sdk apps. I can access settings from the kebab menu and enable discoverable (doesn't work) and if I open some other app and open the share sheet I can select WarpShare but no targets show (my mac airdrop is set to everyone).

**Comment by taesungh** [comment]
After testing a bit more, I found that the phone must also be connected to a wi-fi network to pass the permissions check.
Additionally, it seems that the phone and AirDrop device must be on the same wireless network unlike pure AirDrop 😔

**Comment by Devnol** [comment]
It is, they are.

**Comment by musakahero** [comment]
> After testing a bit more, I found that the phone must also be connected to a wi-fi network to pass the permissions check.
> Additionally, it seems that the phone and AirDrop device must be on the same wireless network unlike pure AirDrop 😔

This helped me get through the permissions screen, it's now empty screen with WarpShare on top and menu button on the side. Once I get to test with an iPhone, I'll see if it appears in the list.
If you're right about then working only on the same wifi network, then that's a sad revelation.

**Comment by arukode** [comment]
> Had this issue initially but quickly resolved by **making sure wi-fi and bluetooth are enabled**. No other permissions needed to be granted besides "Files and media". OnePlus 6, OxygenOS 11.

Same here, OnePlus 7 OxygenOS 12, after enabling Bluetooth, closing and reopening the app, it worked.

**Comment by amirian** [comment]
Same for Motorola moto g52, Android 12. Turning on wifi and Bluetooth doesn't help passing the grant screen
